[project]
name = "pywc"
version = "1.0.0"
description = "Unix 'wc' command implementation in Python"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
]

[project.scripts]
pywc = "pywc:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"